### ISSUE TITLE
Handle blocking

### ISSUE THREAD

**Issue by SystemFw** [ovotech/fs2-kafka-client#15]
I haven't really dug into it, but from the comment in 
https://github.com/ovotech/fs2-kafka-client/blob/master/src/main/scala/com/ovoenergy/fs2/kafka/ConsumerSettings.scala#L8
it looks like the api is blocking (most likely due to wrapping a blocking client). 

If so, we should provide as easy way to shift ops to a dedicated pool, like it's done in fs2-io in the 1.0 version of fs2.

A more radical alternative would be to avoid using the java client like it's done in https://github.com/Spinoco/fs2-kafka , but I'm guessing we get more features this way?

**Comment by filosganga** [comment]
We cannot use the Spinoco fs2-kafka as it does not handle consumers balancing, you need to assign the partition to each node yourself. Most likely you would need something like `etcd`, `consul` or `zookeeper` to assign the partitons to each node but it is far to be trivial.

Regarding the dedicated pool, you are completely right

There is also another possibility that I have been investigated a bit. The async commit works mostly in this way: You request to commit, the consumer sends it to Kafka asynchronously but notifies the callback only in the next call to commit (sync or async). 

I believe it can be modelled with an `IO[IO[Unit]]` or something similar where the outer IO represents the effect to ask to commit, while the inner one will be solved when the commit is actually confirmed by the consumer.

In the meantime, we should use a dedicated pool indeed!!!

**Comment by notxcain** [comment]
Is it possible to use Java client only for consumer balancing and consume assigned partitions using https://github.com/Spinoco/fs2-kafka?
