### ISSUE TITLE
Artifact not found

### ISSUE THREAD

**Issue by jsilva** [ovotech/fs2-kafka-client#16]
using `libraryDependencies += "com.ovoenergy" %% "fs2-kafka-client" % "0.2.2"` yields ResolveException and  https://jcenter.bintray.com/com/ovoenergy/fs2-kafka-client_2.12/ returns
404 was this published ?

Thanks

**Comment by LukaszByczynski** [comment]
Add `"Ovotech" at "https://dl.bintray.com/ovotech/maven"` to your resolvers
