### ISSUE TITLE
Bump to stable fs2 and cats-effect 1.0.0

### ISSUE THREAD

**Issue by LukaszByczynski** [ovotech/fs2-kafka-client#17]
Hi,

Stable Cats-effect was released last week. So I wonder it will be a good idea to release this project with bumped dependencies to reduce annoying fights with evicted resolution errors.

**Comment by SystemFw** [comment]
@LukaszByczynski fs2 is still on M5 (we plan to release 1.0 in October). That being said I have  upgraded some projects, and it's certainly a good idea to start upgrading libraries. It will take a bit more than bumped dependencies though, for example with `ContextShift` we can now handle #15

**Comment by filosganga** [comment]
Hi @LukaszByczynski, 
there is a branch (release-0.2) that is based on cats-1.0.x. It has been released with the 0.2.2 version. 

We will release a new 0.2.x version as soon as fs2 1.0 is released.

Thanks
