### ISSUE TITLE
what is the correct way to handle errors and carry on consuming?

### ISSUE THREAD

**Issue by MarkRBM** [ovotech/fs2-kafka-client#29]
I have a consumer that is running fine but that stops consuming messages if there is ever an exception when handling the message (in my case specifically an avro serialisation message)

I want to log the exception message and then carry on with processing the next message.  If I do nothing the entire stream / IO ends with an unhandled error exception.  So I tried handleErrorWith{e => Stream[F].emit(())} as then result of my stream is UNIT anyway.  This swallows the exception but the next kafka message is never consumed.

What should I be doing to handle the message and then carry on consuming?

**Comment by filosganga** [comment]
It depends on which method you are using.

In the case of `consumeProcessAndCommit`, the effect `F` resulting from processing each record must succeed in order to continue consuming.

You should apply `handleErrorWith` to the effect rather than the `Stream`.

**Comment by MarkRBM** [comment]
oh that makes sense, how do I get it early enough in the chain though? for example my chain is basically `consumeProcessAndCommit[Task](blah)(Task.point((A, B)) through(fromABPipe) to(sendSink)` 
but my error is a serialization error before it gets to my code so if I add handleError to the Task in my sendSink it never gets to it (as far as I can tell) and if I add it to `Task.point((A,B))` I dont know what to actually return from the handleError because it changes the return type
